package com.views;



import com.controllers.Controller;
import com.models.Model;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.Font;


/**
 *
 * @author Ana�s
 */
public class GestionView extends PanelView {

    /**
     * Creates new form NewJPanel
     */
    public GestionView(Controller controleur) {
		super(controleur);
        initComponents(controleur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param controller TODO
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(Controller controller) {

        btnGererReservations = new javax.swing.JButton();
        btnGererVols = new javax.swing.JButton();

        btnGererReservations.setText("Gérer Reservations");

        btnGererVols.setText("Gérer Vols");
        
        Composant composant = new Composant((Controller) controller, new boolean[] {false, false, true});
        
        JLabel lblTitre = new JLabel("Accueil");
        lblTitre.setFont(new Font("Tahoma", Font.PLAIN, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnGererVols, GroupLayout.PREFERRED_SIZE, 174, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(btnGererReservations, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(lblTitre, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
        					.addComponent(composant, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(composant, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblTitre, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE))
        			.addGap(46)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnGererVols, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnGererReservations, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(69, Short.MAX_VALUE))
        );
        this.setLayout(layout);
        
        
        
        // notre code
		// notre code
        btnGererVols.addActionListener(controller);
        btnGererVols.setActionCommand("GestionVol");

        btnGererReservations.addActionListener(controller);
        btnGererReservations.setActionCommand("GestionReservations");
        
    }// </editor-fold>                         

    private void btnGererVolsActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnGererReservations;
    private javax.swing.JButton btnGererVols;
	@Override
	public Model fillAndGetModel() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void displayModel(Model model) {
		// TODO Auto-generated method stub
		
	}                 
}
